### ISSUE TITLE
Purchase Metrics Missing

### ISSUE THREAD

**Issue by ferchackal** [Gladior-B-V/facebook-ads-connector#1]
Hi, I would like to know if there is a way to add WEBSITE PURCHASES and WEBSITE PURCHASES CONVERSION VALUE metrics as I can't find them in the current metrics.

**Comment by daannijkamp** [comment]
Hi @ferchackal,

You're right. They are missing from the fields.
The reason for this is how the way Facebook provides the data in their API is not quite competiable with how Google Data Studio expects the data. We're still working on this. I'll keep you posted when those fields are made available.

cc: @zoedufrenne

**Comment by ferchackal** [comment]
Cool thanks for the quick response. Have a nice week.

Fernando

**Comment by adpesek** [comment]
Hi, I also have problem, that I see 0 conversions (purchases on my website), but I am sure, that there should be more than 0., because I see it at Ads Manager. I also tried another GDS connector and there I see it correctly. Do you have any updates about fixing this? Thank you very much :-) 

<img width="1038" alt="Snímek obrazovky 2021-07-09 v 14 28 19" src="https://user-images.githubusercontent.com/84626839/125078286-78ce5f00-e0c2-11eb-942d-0190078d8795.png">

**Comment by zoedufrenne** [comment]
Hi @adpesek,
No updates yet, we're still working on this. We'll keep you posted when those fields are made available!

**Comment by zoedufrenne** [comment]
Hi @adpesek 
We've made through the year some changes to the connector, but the data field ‘purchase conversion value’ won't be added to our connector. This is because, it is a calculated field from Facebook and the Facebook API doesn’t support these fields. We've updated our support page about the Facebook Ads connector as well. 

Conversions are available in the connector but, we use the default conversion window, this means we use the [“7d_click”,”1d_view”]. If you are using a different conversion window. You won’t get any data. 

In the future we will add a function where you can change the conversion window with additional settings. (probably in a paid version of the Facebook Ads connector).  But for now this way works, see screenshot for example. 

![image](https://user-images.githubusercontent.com/84766152/226875263-220051a5-5d2e-4026-b813-156210793101.png)

For more information about the API from Facebook, https://developers.facebook.com/docs/marketing-api/insights/parameters/v13.0
