### ISSUE TITLE
Outbound clicks (ctr)

### ISSUE THREAD

**Issue by MauiVindevogel** [Gladior-B-V/facebook-ads-connector#20]
Hello, 

I tried to add 'outbound clicks' to my Looker Studio report, using the Gladior BV facebook ads connector but it says 'no data'. When looking at facebook, I do have data for this metric. I also don't see 'outbound clicks ctr' amongst the existing metrics, will this be added in the future?

**Comment by zoedufrenne** [comment]
Hi @MauiVindevogel , Both fields are available in the connector: https://datahub.gladior.com/data-sources/support-facebook-ads-connector/ (see for more information). Which conversion window do you use? 

Custom pixel events aren't measured in the connector and won't be added. This is because the custom pixel events are per customer different and that makes the fields dynamic and hard to add to the connector.

**Comment by MauiVindevogel** [comment]
Hi I hit the 'refresh fields' this morning and outbound clicks and outbound CTR were added all of a sudden :) so it's fixed now, probably a glitch or something, thank you for your help :-)

**Comment by zoedufrenne** [comment]
ah good to hear! thanks for letting us know!
