### ISSUE TITLE
"Leads" are missing

### ISSUE THREAD

**Issue by mmoraes** [Gladior-B-V/facebook-ads-connector#3]
First of all, thanks for this connector. Really helpful!

I'm having no luck while fetching "Leads" or "Website Leads" conversions.

In FB Ads Manager I see them but through the connector in Google Data Studio it's just "zero", no matter the selected date period. 

Other metrics, like "clicks", "reach" etc., work as usual.

**Comment by zoedufrenne** [comment]
Hi, 

Great to hear you like the connector.
Sorry we didn't respond sooner!

Do you still have this issue? We recently made some updates to the connector, maybe this resolved your issue. 
Otherwise we will look to the connector.

**Comment by mmoraes** [comment]
Hi @zoedufrenne, thanks for the reply.

Unfortunately the problem with the FB Ads Connector persists. I can see geographical and demographical data, as well as some basic info, like Clicks, CTR, Impressions etc.

But other events, like "Lead", "Registration" and "Purchase", are still incorrect and always shown as ZERO.

**Comment by zoedufrenne** [comment]
Hi, 

In the Facebook Ads Connector we’re using the standard attribute model. The Standard attribute model is "7-day click and 1-day view".
When your Facebook campaigns use a different Attribute model, the data will come back as ZERO.

It’s possible for us to make a different connector, but it will take a lot more time. Therefor we won’t update the free Facebook Connector, because we are using the standard Attribute model. If you would like a custom Facebook Ads Connector, we could plan a meeting and check what the possibilities are.

If you have any questions, please let me know!

**Comment by mmoraes** [comment]
Hi @zoedufrenne, thanks again but even though I run the standard attribution model (7D click & 1D view) I still see zeroed values in conversion events like Purchase, Cost Purchases, Lead, Cost Leads etc. in Data Studio. 

Do you have any working demo with these events loading fine? Just so I can duplicate it and see what it's different from my Data Studio report. 

Thanks.
