### ISSUE TITLE
filter ad set name facebook ads

### ISSUE THREAD

**Issue by charlenej13** [Gladior-B-V/facebook-ads-connector#32]
Hi,
i would like to add a filter for my ad sets.
I want to create a filter with "ad sets name **contains** ...."
and i don't want to use "ad sets name **IS** ...."
And it doesn't work.
<img width="933" alt="Capture d’écran 2024-04-09 à 16 29 09" src="https://github.com/Gladior-B-V/facebook-ads-connector/assets/166526492/ca4a06a7-9bb3-4704-8866-1a0bd1c522b7">
<img width="934" alt="Capture d’écran 2024-04-09 à 16 29 03" src="https://github.com/Gladior-B-V/facebook-ads-connector/assets/166526492/68dba4de-c2ed-4943-8923-8138ad768c37">

**Comment by zoedufrenne** [comment]
Hi @charlenej13 I checked in our dashboards but the filter option is working. So I can't recreate the issue. Is it the correct spelling for the adset name? can you try to filter first with just one metric like impressions and see if it's works? It is possible that some of the used metrics you can't filter and that's why the filter isn't working.

**Comment by charlenej13** [comment]
Hi @zoedufrenne are you french ?
I tried with a table with only impressions, it was not working.
But I edited my filter and used "contains" but you must write exactly the same (with the capitals letters and normal letters) and now it's working :)

**Comment by zoedufrenne** [comment]
Hi @charlenej13 no Dutch, good to hear it worked. It's nescessary in Looker Studio to write the exact match even when it's contains.

**Comment by charlenej13** [comment]
thank you very much :) have a good day
